### ISSUE TITLE
SocialAuth Missing AppSection directory

### ISSUE THREAD

**Issue by Gigiart** [apiato/social-auth-container#1]
On SocialAuth AppSection is missing in SocialAuth\Tasks :
`use App\Containers\User\Data\Repositories\UserRepository;`
should be:
`use App\Containers\AppSection\User\Data\Repositories\UserRepository;`

**Comment by Mohammad-Alavi** [comment]
Thank you! [Fixed](https://github.com/apiato/social-auth-container/commit/8c0a836edc45f946b46abc9894ff6489ee16e1b9).
